version: '3.8'

services:
  mysql:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8070:8070"
